Portuguese lang
TerraFirmaCraft/TerraFirmaCraft pull request #1163
Opened 2020-05-03 22:05 UTC by GustavoLongatto

The translation is practically ready. Some plants and settings have not yet been changed

2020-05-05 10:50 UTC, DisasterMoo requested changes
Português:
Primeiro queria dizer que sou brasileiro e trabalho com a equipe de desenvolvimento do TerraFirmaCraft, portanto, posso fazer revisões à essa PR e te ajudar a deixar a tradução melhor.
Dito isso, ótimo trabalho! Faltam alguns pedaços para traduzir e contém alguns erros de digitação, seguem eles (os comentários em si vão ser em português):

English:
First, I would like to say I'm brazilian and I work with TerraFirmaCraft's development team, therefore, I can do reviews to this PR and make this translation better.
That said, good job! There's missing a few pieces to translate and also a few typos (the comments will be in portuguese):

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +tfc.command.playertfc.usage_cant_set_add_nutrients=Can't set / add nutrients directly as it's based on food history. Run /playertfc reset nutrients instead.
Faltou traduzir

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +tfc.command.playertfc.get_nutrients_last_eaten=por Último Eaten: %d Hunger, %s Saturation, %s Decay Modifier.
Aqui também

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +tfc.tooltip.anvil_tier_too_low=A bigorna possui categoria muito baixa!
```suggestion
tfc.tooltip.anvil_tier_too_low=O nível da bigorna é muito baixa!
```

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +tfc.tooltip.anvil_not_weldable=Os itens são podem ser soldados!
```suggestion
tfc.tooltip.anvil_not_weldable=Os itens não podem ser soldados!
```

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +tfc.tooltip.firepit_cooking_pot_waiting=Adicione Ingrdientes
```suggestion
tfc.tooltip.firepit_cooking_pot_waiting=Adicione Ingredientes
```

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +tfc.key.placeblock=Place Item Holder Block
Tradução

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +config.tfc.general.disableFallableBlocksHurtEntities.tooltip=Se verdadeiro, blocos em queda (ie: terra, pedra) não causarão dano.
`ie` em inglês significa exemplo, mesma coisa para `eg` se tiver algum mais.
```suggestion
config.tfc.general.disableFallableBlocksHurtEntities.tooltip=Se verdadeiro, blocos em queda (exemplo: terra, pedra) não causarão dano.
```

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +config.tfc.general.removeVanillaRecipes=Remover receitas do Vanilla
```suggestion
config.tfc.general.removeVanillaRecipes=Remover receitas de craft do Vanilla
```

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +config.tfc.general.removeVanillaLoots.tooltip=Enable/Disable the vanilla loot entries that conflict with TFC (ie: potatoes). False = Those loot entries are left in place.
Tradução

2020-05-05 10:50 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +config.tfc.general.nutritionRotationHungerWindow.tooltip=This is the amount of hunger (consumed) required for a player to completely refresh their nutrition stats. In TFC, almost all foods have 4 hun
Tradução

2020-05-05 10:52 UTC, DisasterMoo commented on src/main/resources/assets/tfc/lang/pt_br.lang
> +config.tfc.general.nutritionRotationHungerWindow.tooltip=This is the amount of hunger (consumed) required for a player to completely refresh their nutrition stats. In TFC, almost all foods have 4 hun
Dei uma pausa aqui por perceber que tem ainda mais coisa faltando, mas quando você achar que está bom o suficiente, marque todas as conversas como resolvidas que irei continuar minha revisão.

2020-05-05 11:09 UTC, GustavoLongatto commented
Vou terminar a tradução e já adiciono o arquivo, agora falta pouco para
acabar.

Em ter, 5 de mai de 2020 07:52, DisasterMoo <notifications@github.com>
escreveu:

> *@DisasterMoo* commented on this pull request.
> ------------------------------
>
> In src/main/resources/assets/tfc/lang/pt_br.lang
> <https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/1163#discussion_r420021615>
> :
>
> > +config.tfc.general.forceReplaceVanillaAnimals.tooltip=If true, this will replace vanilla animals with the TFC counterpart under any spawning circumstances (ie: mob spawner, etc).
>
> +
>
> +config.tfc.general.peacefulDifficultyPassiveRegeneration=Peaceful Difficulty Passive Stats Regen
>
> +config.tfc.general.peacefulDifficultyPassiveRegeneration.tooltip=Should the player receive passive regeneration of health, food, and thirst, while in peaceful mode similar to vanilla?
>
> +
>
> +config.tfc.general.requireHammerInOffHand=Chisel requires hammer in offhand
>
> +config.tfc.general.requireHammerInOffHand.tooltip=If true, hammer must be in offhand for chisel use. If false, hammer can be in offhand or toolbar.
>
> +
>
> +config.tfc.general.chiselDelay=Chisel has a delay
>
> +config.tfc.general.chiselDelay.tooltip=Does the chisel have a delay on use?
>
> +
>
> +config.tfc.general.worldRegenerationMinimumTime=World Regeneration Min Time
>
> +config.tfc.general.worldRegenerationMinimumTime.tooltip=The minimum time for a chunk to be unoccupied for it's resources to begin to naturally regenerate. (In days). After this amount, regeneration will scale up based on how long since this duration, up to a maximum of 4x
>
> +
>
> +config.tfc.general.worldRegenerationSticksRocksModifier=World Regeneration Debris Modifier
>
> +config.tfc.general.worldRegenerationSticksRocksModifier.tooltip=The weight for loose rocks and sticks regeneration in the world.
>
> +
>
> +config.tfc.general.foodDecayStackTime=Food Decay Stack Time
>
> +config.tfc.general.foodDecayStackTime.tooltip=The number of hours to which initial food decay will be synced. When a food item is dropped, it's initial expiration date will be rounded to the closest multiple of this (in hours).
>
> +
>
> +config.tfc.general.foodPassiveExhaustionMultiplier=Hunger Passive Exhaustion Multiplier
>
> +config.tfc.general.foodPassiveExhaustionMultiplier.tooltip=A multiplier for passive exhaustion (how fast your hunger decays. 0 = hunger doesn't decay passively, higher values = faster decay.
>
> +
>
> +config.tfc.general.oreDictIron=Iron Ore Dictionary in Wrought Iron
>
> +config.tfc.general.oreDictIron.tooltip=Add iron ore dictionary to wrought iron items?
>
> +
>
> +config.tfc.general.oreDictPFim do=PFim do Ore Dictionary in Sheets
>
> +config.tfc.general.oreDictPFim do.tooltip=Add pFim do ore dictionary to sheet items?
>
> +
>
> +config.tfc.general.spawnProtectionEnable=Enable Spawn Protection
>
> +config.tfc.general.spawnProtectionEnable.tooltip=Should living in a chunk block hostile mob spawning over time?
>
> +
>
> +config.tfc.general.spawnProtectionMinY=Spawn Protection Minimum Y Level
>
> +config.tfc.general.spawnProtectionMinY.tooltip=The min Y value a spawn has to be for spawn protection to be considered. (spawns under this level won't be stopped by spawn protection.
>
> +
>
> +config.tfc.general.charcoalPitTime=Charcoal Pit Ticks
>
> +config.tfc.general.charcoalPitTime.tooltip=The time required for a charcoal pit to complete
>
> +
>
> +config.tfc.general.defaultMonthLength=Default Month Length
>
> +config.tfc.general.defaultMonthLength.tooltip=The default length of a month (in days) when a new world is started. This can be changed in existing worlds via the /timetfc command.
>
> +
>
> +config.tfc.general.enableAnimalAging=Enable Aging Animals
>
> +config.tfc.general.enableAnimalAging.tooltip=Should animals became old and die?
>
> +
>
> +config.tfc.general.factorAnimalAging=Animal Aging Factor
>
> +config.tfc.general.factorAnimalAging.tooltip=How long animals until animals became old (in factor to adulthood)?
>
> +
>
> +config.tfc.general.chanceAnimalDeath=Animal Death Chance
>
> +config.tfc.general.chanceAnimalDeath.tooltip=Chance of animal dying (checked every in-game day) after it became old
>
> +
>
> +config.tfc.general.stoneAxeLogReturnRate=Stone Axe Madeira de Return Rate
>
> +config.tfc.general.stoneAxeLogReturnRate.tooltip=Madeira de return rate of stone axes (eg: How efficiently it is)
>
> +
>
> +config.tfc.general.inventoryCraftingTableMode=Inventory Crafting Table
>
> +config.tfc.general.inventoryCraftingTableMode.tooltip=Enable a 3x3 crafting inventory via key binding. 0 = Disabled, 1 = Enabled, Always, 2 = Enabled, If the player has a crafting table in inventory. (ore dictionary name: 'workbench')
>
> +
>
> +config.tfc.general.tankSmallVessel=Small Vessel Tank Storage
>
> +config.tfc.general.tankSmallVessel.tooltip=How much metal (units / mB) can a small vessel hold?
>
> +
>
> +config.tfc.general.tankBarrel=Barrel Tank Storage
>
> +config.tfc.general.tankBarrel.tooltip=How much fluid (mB) can a barrel hold?
>
> +
>
> +config.tfc.general.tankCrucible=Crucible Tank Storage
>
> +config.tfc.general.tankCrucible.tooltip=How much metal (units / mB) can a crucible hold?
>
> +
>
> +config.tfc.general.disableCobbleGenOverride=Disable TFC Pedregulho de Generation Changes
>
> +config.tfc.general.disableCobbleGenOverride.tooltip=Turn this on if you want to edit this with other mods or have a way to get vanilla cobblestone.
>
> +
>
> +config.tfc.general.leafMovementModifier=Leaf Movement Modifier
>
> +config.tfc.general.leafMovementModifier.tooltip=Leaf block movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down. (Speed * this = slow)
>
> +
>
> +config.tfc.general.berryBushMovementModifier=Berry Bush Movement Modifier
>
> +config.tfc.general.berryBushMovementModifier.tooltip=Berry bush movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down. (Speed * this = slow)
>
> +
>
> +config.tfc.general.snowMovementModifier=Snow Movement Modifier
>
> +config.tfc.general.snowMovementModifier.tooltip=Generic snow movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down.
>
> +
>
> +config.tfc.general.minimumPlantMovementModifier=Minimum Plant Movement Modifier
>
> +config.tfc.general.minimumPlantMovementModifier.tooltip=Generic movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down. Note: this is a little different than other densities (leaf / berry bush), because this actually functions as a maximum slow down. Actual value is dependent on the plant and it's age.
>
> +
>
> +config.tfc.general.disableTorchOverride=Disable Torch Override
>
> +config.tfc.general.disableTorchOverride.tooltip=Turn this on if you want to edit this with other mods.
>
> +
>
> +config.tfc.general.disableTreeFelling=Disable Tree Felling
>
> +config.tfc.general.disableTreeFelling.tooltip=Turn this on if you want to edit this with other mods.
>
> +
>
> +config.tfc.general.woodenBucketWhitelist=Wooden Bucket Fluid Whitelist
>
> +config.tfc.general.woodenBucketWhitelist.tooltip=Allowed fluids to be picked up by the wooden bucket.
>
> +
>
> +config.tfc.general.drinkDelay=Drink Delay
>
> +config.tfc.general.drinkDelay.tooltip=Delay (in ticks) for drinking water by hand
>
> +
>
> +config.tfc.general.blueSteelBucketWhitelist=Blue Steel Bucket Whitelist
>
> +config.tfc.general.blueSteelBucketWhitelist.tooltip=List of fluids allowed to be picked up by blue steel bucket
>
> +
>
> +config.tfc.general.redSteelBucketWhitelist=Red Steel Bucket Whitelist
>
> +config.tfc.general.redSteelBucketWhitelist.tooltip=List of fluids allowed to be picked up by red steel bucket
>
> +
>
> +config.tfc.general.nutritionRotationHungerWindow=Nutrition Rotation Hunger Window
>
> +config.tfc.general.nutritionRotationHungerWindow.tooltip=This is the amount of hunger (consumed) required for a player to completely refresh their nutrition stats. In TFC, almost all foods have 4 hunger, so this is 4x [number of foods required to refresh nutrition [...]

2020-05-05 22:31 UTC, alcatrazEscapee approved these changes

2020-05-06 01:24 UTC, GustavoLongatto commented
Acabo de enviar o arquivo já todo traduzido. Peço desculpas caso eu tenha
feito como me pediu, ainda estou me adaptando ao github.

Em ter., 5 de mai. de 2020 às 19:31, alcatrazEscapee <
notifications@github.com> escreveu:

> *@alcatrazEscapee* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/1163#pullrequestreview-406200584>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEWVJXIZVTZBUTUWF2QRACLRQCHVRANCNFSM4MYJ43UA>
> .
>

2020-05-07 12:44 UTC, DisasterMoo approved these changes
Tudo ok, bom trabalho! Irei adicionar a linguagem PT-BR ao TFC no próximo build.

Assim como nos outros idiomas, sempre que nós mudamos ou adicionamos coisas ao TFC elas ficam desatualizadas ou podem precisar de mudanças. Eu mesmo vou tentar manter a PT-BR atualizada mas se você notar algo faltando tem toda a liberdade de fazer mais um PR.

2020-05-07 12:56 UTC, GustavoLongatto commented
Obrigado por tudo! Fico muito feliz que tenha um brasileiro trabalhando em um projeto tão bom, o trabalho de vcs é excelente. Mal posso esperar para jogar em outras versões.
Abraço

2020-05-07 20:22 UTC, merged