Add TOP plugin info
TerraFirmaCraft/TerraFirmaCraft pull request #1170
Opened 2020-05-04 15:04 UTC by AnodeCathode

Slightly different implementation to Waila as TOP doesn't support annotations. Otherwise follows the setup of the Waila impl.

CTRL+C / CTRL+V to the rescue

2020-05-05 16:01 UTC, DisasterMoo requested changes
Two things:
- Don't duplicate `@Mod` annotation, that will make our jar contains two mods. Use `TerraFirmaCraft#preInit()` and check if TOP is loaded there before passing on the registration to `TOPPlugin`
- Centralize the code that does "waila" stuff: Create a class for every provider with header / body / tail or anything more that is needed with common code there (you may use waila ones, just remove waila specific code there and create these specifics in another class). Functions should receive the `TileEntity`, `Block`, maybe `World` and `BlockPos`, anything that would be needed to work and returns a `List<String>` containing the tooltips that you may convert it to HWYLA or TOP in it's specific class. 

You may think it's a PITA to do the 2nd one but it will make our life maintaining this code later much easier (just one place to change instead of 2 or more. Animals is a "good" bad example of this since I always have to copy paste things there. I can't properly extend vanilla and use our common code in one place since it needs variables saved in the entity's NBT).

2020-05-05 16:01 UTC, DisasterMoo commented on src/main/java/net/dries007/tfc/compat/top/TOPPlugin.java
> +    }
Instead of duplicating pre init event making our jar contains two mods, just pass on the preInit event to this class if TOP mod is present (this is necessary since there's no annotation method in TOP). Also, your `@Optional` annotation will be unnecessary after this change.

2020-05-05 22:34 UTC, alcatrazEscapee requested changes

2020-05-05 22:34 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/compat/top/BlastFurnaceProvider.java
> +                int temperature = blastFurnace.getField(TEBlastFurnace.FIELD_TEMPERATURE);
Two things need to be modified here:
 - We do not sync fields by default when the container is not open, meaning this will suffer from a desync. There are two things needed to resolve this:
   - If TOP has a sync mechanism for TEs that it's looking at, we need to exploit that, or otherwise allow that to sync
   - Based on what sync is happening, this may need to be changed to use other data (for instance, the NBT data directly, see how walia handles it)

2020-05-05 22:34 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/compat/top/CrucibleProvider.java
> +            int temperature = crucible.getField(TECrucible.FIELD_TEMPERATURE);
Same issue as blast furnace.

2020-05-05 22:35 UTC, alcatrazEscapee commented
> You may think it's a PITA to do the 2nd one but it will make our life maintaining this code later much easier (just one place to change instead of 2 or more.

I'm not sure how simple this will be to do, given the API hooks for both cases have potential to be radically different. So if this can be done, great. Otherwise I'm fine with copy paste on this one.

2020-05-06 23:09 UTC, DisasterMoo commented
Closing this in favor of #1209

2020-05-06 23:09 UTC, closed without merging