New animals
TerraFirmaCraft/TerraFirmaCraft pull request #1516
Opened 2020-08-02 12:56 UTC by Abdyman

new animal update, lots of changes sending over to start review
- still pending sounds will send another update hopefully tomorrow with finalized sounds

2020-08-03 16:21 UTC, alcatrazEscapee requested changes
Need to fix merge conflicts. Need to also fix the pile of extra changes that have found their way into this PR:
- You should not be modifying `CodeStyle.xml`, nor anything in `build.gradle`, nor any of `generateResources.py`. None of those are relavant to this PR. In a similar manner there are many changes that need to be resolved with the main branch as they already exist. Please fix these as it will reduce the diff (and thus required review) signifigantly.

2020-08-04 02:00 UTC, HeartyYF commented on src/main/resources/assets/tfc/lang/en_us.lang
> +config.tfc.animals.bear=Grizzly Bear
Only here, the key remains to be bear?

2020-08-04 16:52 UTC, DisasterMoo commented
This commit: https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/1516/commits/9f592cc846de1b247c571706c7a1290a381dcbc9
is basically a copy-paste of changes made in the main repository. I recommend removing it and properly doing a merge in your branch.

2020-08-06 05:23 UTC, Abdyman commented
closing this request, to push new one from new branch

2020-08-06 05:23 UTC, closed without merging