crafting tables
TerraFirmaCraft/TerraFirmaCraft pull request #1755
Opened 2021-04-14 20:27 UTC by eerussianguy

2021-04-15 13:06 UTC, Rongmario requested changes
I don't have TFC workspace up yet but it seems like a custom ContainerType isn't really needed.

Reason: `ContainerType` does have a default `ContainerType.IFactory` (that can be instantiated on `ContainerType#create` but you can still direct a different `Container` to be opened.

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/client/screen/TFCCraftingScreen.java
> +public class TFCCraftingScreen extends ContainerScreen<TFCWorkbenchContainer> implements IRecipeShownListener
It's enough to extend `CraftingScreen`, see: comment in `TFCWorkbenchContainer`.

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/common/blocks/wood/TFCCraftingTableBlock.java
> +public class TFCCraftingTableBlock extends Block implements IForgeBlockProperties
Extend `CraftingTableBlock` and override `INamedContainerProvider#getContainer` to use the custom `WorkbenchContainer` extension.

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/common/container/TFCContainerProviders.java
> +    public static final INamedContainerProvider WORKBENCH = Helpers.createNamedContainerProvider(new TranslationTextComponent("container.crafting"), (windowId, inv, player) -> new TFCWorkbenchContain
Not needed because of the solution.

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/common/container/TFCWorkbenchContainer.java
> +public class TFCWorkbenchContainer extends RecipeBookContainer<CraftingInventory>
Extend `WorkbenchContainer`.

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/common/container/TFCWorkbenchContainer.java
> +    public boolean stillValid(PlayerEntity playerIn)
Once extended, only override this method and leave this implementation.

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/common/blocks/wood/TFCCraftingTableBlock.java
> +public class TFCCraftingTableBlock extends Block implements IForgeBlockProperties
(P.S - I don't know what that name could be with your mappings)

2021-04-15 13:06 UTC, Rongmario commented on src/main/java/net/dries007/tfc/common/blocks/wood/TFCCraftingTableBlock.java
> +            NetworkHooks.openGui((ServerPlayerEntity) player, TFCContainerProviders.WORKBENCH, pos);
Can still use `NetworkHooks#openGui` here, but point it again to the aforementioned `INamedContainerProvider#getContainer`. I think the vanilla `use` method is enough though.

2021-04-26 22:38 UTC, alcatrazEscapee commented
I didn't know `SimpleNamedContainerProvider` existed, but looking at it, we probably don't need `Helpers.createNamedContainerProvider`... whoops.

2021-05-14 01:12 UTC, merged