Finding Dory
TerraFirmaCraft/TerraFirmaCraft pull request #1823
Opened 2021-10-22 21:32 UTC by eerussianguy

2021-10-24 20:39 UTC, alcatrazEscapee requested changes
Looks quite good.

2021-10-24 20:39 UTC, alcatrazEscapee commented on resources/constants.py
> +}"""
These comments are todo or unused?

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/entities/Fauna.java
> +        entity = (EntityType<Mob>) ForgeRegistries.ENTITIES.getValue(new ResourceLocation(GsonHelper.getAsString(json, "entity")));
```suggestion
        entity = (EntityType<Mob>) JsonHelpers.getRegistryEntry(json, "entity", ForgeRegistries.ENTITIES);
```

Similar for below. In addition, as a tip, you can call all vanilla `GsonHelper` methods through `JsonHelpers` as well, i.e. `JsonHelpers.getAsInt()` works fine.

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/entities/Fauna.java
> +        return SpawnPlacements.Type.ON_GROUND;
`JsonHelpers.getEnum` exists that should work for this.

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/entities/Fauna.java
> +public class Fauna
So a couple things
- I worry this is a bit too specific to water spawning. i.e. `fluid`, `distanceBelowSeaLevel`, `solidGround`, etc. It might be better to have a type dispatch system?
- The other thing would be I'm not sure what you mean by spawn predicates - the goal here is to have additional end-user configurability of spawn checks, correct? What is vanilla changing about that?

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/entities/FaunaManager.java
> +public class FaunaManager extends DataManager<Fauna>
This looks like it should be a `RegisteredDataManager`, not a `DataManager`. Reason being:

- when you register a `SpawnPlacements`, you can register a "rules" instance that holds the `Supplier<Fauna>`, and resolves it at the correct time. Then, you don't need the accessor mixin, don't need the `postProcess`, etc. See `ClimateRanges`

```java
// this only needs to be called once, since the supplier will get reloaded automatically when resources reload
Supplier<Fauna> fishFauna = Fauna.MANAGER.register("fish");
SpawnPlacements.register(new FaunaSpawnPredicate(fishFauna));

class FaunaSpawnPredicate extends SpawnPlacements.SpawnPredicate<Mob> {
    FaunaSpawnPredicate(Supplier<Fauna> fauna) { ... }

    // do the predicate stuff, calling `fauna.get()`
}


```

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/entities/aquatic/IBucketableOceanFish.java
> +public interface IBucketableOceanFish
This apparently needs to be deleted?

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/entities/Fauna.java
> +        this.fluid = ForgeRegistries.FLUIDS.getValue(new ResourceLocation(GsonHelper.getAsString(json, "fluid", "minecraft:empty")));
Looking further at this - it seems salt water vs. fresh water is pretty hardcoded into our fishies. So having json exposed "fluid" wouldn't be particularly useful. So maybe it's best to just scrap this completely, and define either type-dispatched or just the spawn rule type?

2021-10-24 20:39 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/mixin/accessor/SpawnPlacementsAccessor.java
> +public interface SpawnPlacementsAccessor
With the tweak to fauna above, we don't need to re-register these so this should be fine to remove.

2021-10-24 20:42 UTC, eerussianguy commented on resources/constants.py
> +}"""
todo, just makes my life easier later

2021-10-27 13:06 UTC, alcatrazEscapee commented on resources/data.py
> +    return utils.del_none({
`del_none` shouldn't be necessary here I don't think, since it'll eventually be called by `utils.write`

2021-11-01 12:57 UTC, merged