Fix thatch bed drops & ice pile rendering (1.18)
TerraFirmaCraft/TerraFirmaCraft pull request #1924
Opened 2022-04-02 00:20 UTC by Charnuz

Before:
![before-ice-fix](https://user-images.githubusercontent.com/16440978/161356339-1547a18c-56c8-4876-abb7-a3ac1994ffa7.png)
After:
![after-ice-fix](https://user-images.githubusercontent.com/16440978/161356344-be2845a3-893a-4dd4-8faf-d7c7a1be4819.png)

2022-04-03 15:19 UTC, eerussianguy requested changes

2022-04-03 15:19 UTC, eerussianguy commented on src/main/java/net/dries007/tfc/common/blocks/TFCBlocks.java
> +    public static final RegistryObject<Block> THATCH_BED = register("thatch_bed", () -> new ThatchBedBlock(ExtendedProperties.of(Properties.of(Material.REPLACEABLE_PLANT).sound(TFCSounds.THATCH).stre
flammable?

2022-04-03 15:19 UTC, eerussianguy commented on src/main/java/net/dries007/tfc/mixin/IceBlockMixin.java
> +    }
Can you inject at head here, set to true and cancel instead? Overrides should be avoided

2022-04-03 15:19 UTC, eerussianguy commented on src/main/java/net/dries007/tfc/util/InteractionManager.java
> +                            world.getBlockEntity(headPos, TFCBlockEntities.THATCH_BED.get()).ifPresent(entity -> entity.setBed(headState, baseState, stack.split(1)));
may as well change this param to level while you are here

2022-04-07 02:40 UTC, Charnuz commented on src/main/java/net/dries007/tfc/TerraFirmaCraft.java
> +        TFCLoot.registerAll(bus);
Can register each registry individually if preferred

2022-04-07 04:00 UTC, eerussianguy approved these changes

2022-04-07 12:02 UTC, alcatrazEscapee approved these changes

2022-04-07 16:30 UTC, merged