Fixed #1956 by implementing shield textures, animations and properties
TerraFirmaCraft/TerraFirmaCraft pull request #1965
Opened 2022-05-28 23:11 UTC by neumann-lukas

Changes over 1.12:
- Copied shield model jsons from 1.12
- added `"gui_light": "front",` to all model jsons
- Implemented ` ItemProperties.register` in the Item init. #1956 

Therefor fixed #1956 .

2022-05-28 23:29 UTC, alcatrazEscapee requested changes
Thank you very much for the contribution! I just have two suggestions, the latter seems like it applies to most/all the models included.

2022-05-28 23:29 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/items/TFCShieldItem.java
> +        }
Prefer grouping this with our other registrations of this type in [ClientEventHandler](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/5750590698c490b91d4a1526cf9e866b59836264/src/main/java/net/dries007/tfc/client/ClientEventHandler.java#L145-L176)

2022-05-28 23:29 UTC, alcatrazEscapee commented on src/main/resources/assets/tfc/models/item/metal/shield/bismuth_bronze.json
> +        "north": {"uv": [0, 0, 0, 0], "texture": "#texture"},
The `#missing` textures could probably be removed from the models entirely here.

2022-05-29 13:19 UTC, neumann-lukas commented
Should be finished now :-)

2022-05-29 16:29 UTC, merged