Improve barrel recipes
TerraFirmaCraft/TerraFirmaCraft pull request #2220
Opened 2022-11-03 18:33 UTC by pehala

* Do not create more fluid in Barrel than its capacity
Example recipe for which the current code is incorrect:
```
{
  "type": "tfc:barrel_instant",
  "input_item": {
    "ingredient": {
      "item": "tfc:powder/flux"
    }
  },
  "input_fluid": {
    "ingredient": "minecraft:water",
    "amount": 500
  },
  "output_fluid": {
    "fluid": "tfc:limewater",
    "amount": 1000
  }
}
```
* Do not erase barrel output fluid if it is the same as the recipes
  * Means duplication recipes (like Firmalife yeast) will work correctly, and the input won't get erased. 
```
{
  "type": "tfc:barrel_sealed",
  "input_item": {
    "ingredient": {
      "tag": "tfc:makes_tannin"
    }
  },
  "input_fluid": {
    "ingredient": "tfc:tannin",
    "amount": 100
  },
  "output_fluid": {
    "fluid": "tfc:tannin",
    "amount": 500
  },
  "duration": 12
}
```

## TODO
- [ ] Tests

Before fully committing and writing tests, I wanted to ask if this is even something you would be willing to accept.

2022-11-03 18:37 UTC, alcatrazEscapee commented
Can you explain in more detail what the problems here are? i.e. what is the exact recipe setup; what is the erroneous state, and what is the corrected version?

2022-11-03 18:49 UTC, pehala commented
> Can you explain in more detail what the problems here are? i.e. what is the exact recipe setup; what is the erroneous state, and what is the corrected version?

Of course, sorry I didn't properly explain in the description:

## Issue 1: Do not create more fluid in Barrel than its capacity
 * Recipe:
```
{
  "type": "tfc:barrel_instant",
  "input_item": {
    "ingredient": {
      "item": "tfc:powder/flux"
    }
  },
  "input_fluid": {
    "ingredient": "minecraft:water",
    "amount": 500
  },
  "output_fluid": {
    "fluid": "tfc:limewater",
    "amount": 1000
  }
}
```
* Current: 10000 water + 20 flux -> 10000 limewater + 0 flux
   * It calculated the recipe for 10000 input water which results in 20000 limewater, which is then trimmed to only 10000 output. 
* New: : 10000 water + 20 flux -> 10000 limewater + 10 flux
  * It didn't consume all flux and only changed 10 flux into the limewater. Sadly the rest of the water is lost but I still think it is better than before.

## Issue 2: Do not erase barrel output fluid if it is the same as the recipes 
* Recipe:
```
{
  "type": "tfc:barrel_sealed",
  "input_item": {
    "ingredient": {
      "tag": "tfc:makes_tannin"
    }
  },
  "input_fluid": {
    "ingredient": "tfc:tannin",
    "amount": 100
  },
  "output_fluid": {
    "fluid": "tfc:tannin",
    "amount": 500
  },
  "duration": 12
}
```
* Current: 9000 tannin + 1 log -> 500 tannin
   * The tannin got completely replaced by the new output
* New: 9000 tannin + 1 log -> 9500 tannin
   * The tannin is added to the existing input

2022-11-04 11:18 UTC, alcatrazEscapee commented
Both of these sound reasonable to me. Please use our code style (brackets on newlines, fields and variables in `lowerCamelCase`, etc.).

2022-11-04 11:57 UTC, pehala commented
> Both of these sound reasonable to me. Please use our code style (brackets on newlines, fields and variables in `lowerCamelCase`, etc.).

Fixed

2022-11-05 15:01 UTC, alcatrazEscapee requested changes

2022-11-05 15:01 UTC, alcatrazEscapee commented on src/main/java/net/dries007/tfc/common/recipes/BarrelRecipe.java
> +                int max_multiplier = capacity / outputFluid.getAmount();
```suggestion
                int maxMultiplier = capacity / outputFluid.getAmount();
```

2022-11-05 18:17 UTC, pehala commented
* Added basic tests for the two cases I fixed
  * Required adding Mockito as test dependency, but I believe it is ok
* Fixed `maxMultiplier` name

2022-11-07 22:08 UTC, pehala commented
Based on our discussion, I removed the tests and stashed them. If you want I can create a separate PR for that where deeper discussion regarding tests can be held.

2022-11-24 19:13 UTC, merged