Add support for Antique Atlas
TerraFirmaCraft/TerraFirmaCraft pull request #2333
Opened 2023-03-09 17:02 UTC by Jummit

Instead of looking empty, the antique atlas now looks like this:

![Screenshot from 2023-03-09 17-54-15](https://user-images.githubusercontent.com/28286961/224100760-66ca3f8f-28f7-4b70-bc56-320383c2be85.png)

I didn't add any custom terrain textures because I felt the vanilla ones fit fairly well.

2023-03-09 17:22 UTC, alcatrazEscapee commented
Thanks! This should be a fairly straightforward addition to our existing data generation, yes, and I'd be happy to have this compat.

2023-03-09 17:23 UTC, Jummit commented
> Thanks! This should be a fairly straightforward addition to our existing data generation, yes, and I'd be happy to have this compat.

I'm working on it right now, what would be a good way to guarantee that new biomes are added to the atlas data files?

2023-03-09 17:26 UTC, alcatrazEscapee commented
Add the atlas type as a parameter to `biome()`, and generate the file there:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/af1e782067e62ce1d9bffa3c2db5a88216551790/resources/world_gen.py#L1247

Then change the callsites:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/af1e782067e62ce1d9bffa3c2db5a88216551790/resources/world_gen.py#L56-L88

2023-03-09 19:16 UTC, Jummit commented
I've implemented the data generation.

2023-03-10 02:15 UTC, eerussianguy approved these changes

2023-03-10 03:04 UTC, eerussianguy requested changes
you can see resource validation fails because there's a diff between when you run `resources all` and the current state. please regen resources.

2023-03-10 08:28 UTC, Jummit commented
> you can see resource validation fails because there's a diff between when you run `resources all` and the current state. please regen resources.

Done.

2023-03-11 03:55 UTC, merged